In [1]:
### Defining Matrix

In [3]:
import numpy as np

In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
x.shape

(2, 3)

In [7]:
np.random.randint(0, 10,(2, 3))

array([[2, 8, 4],
       [6, 6, 2]])

In [10]:
np.random.randint(1, 10,(3, 3))

array([[2, 2, 6],
       [1, 5, 7],
       [6, 5, 8]])

In [12]:
##Addition of Matrices

In [14]:
a = np.random.randint(1, 100,(5, 4))
b = np.random.randint(1, 100,(5, 4))
print(a)
print(b)


[[90 48 16 47]
 [68 51 37 70]
 [ 4 40 85 85]
 [94 15  6 68]
 [21 57 71 31]]
[[99 10 71 19]
 [ 9 70 79 77]
 [48 88 75 63]
 [36 91 31 82]
 [51 18 79 41]]


In [15]:
a + b

array([[189,  58,  87,  66],
       [ 77, 121, 116, 147],
       [ 52, 128, 160, 148],
       [130, 106,  37, 150],
       [ 72,  75, 150,  72]])

In [18]:
###Subtraction of Matrices

In [19]:
a - b

array([[ -9,  38, -55,  28],
       [ 59, -19, -42,  -7],
       [-44, -48,  10,  22],
       [ 58, -76, -25, -14],
       [-30,  39,  -8, -10]])

In [20]:
###Division of Matrices

In [21]:
a / b

array([[0.90909091, 4.8       , 0.22535211, 2.47368421],
       [7.55555556, 0.72857143, 0.46835443, 0.90909091],
       [0.08333333, 0.45454545, 1.13333333, 1.34920635],
       [2.61111111, 0.16483516, 0.19354839, 0.82926829],
       [0.41176471, 3.16666667, 0.89873418, 0.75609756]])

In [22]:
###Multiplication ... Hadamard Multiplication

In [23]:
a * b

array([[8910,  480, 1136,  893],
       [ 612, 3570, 2923, 5390],
       [ 192, 3520, 6375, 5355],
       [3384, 1365,  186, 5576],
       [1071, 1026, 5609, 1271]])

In [24]:
###More on Hadamard Multiplication 

In [25]:
a = np.random.randint(1, 10,(2, 2))
b = np.random.randint(1, 10,(2, 2))
print(a)
print(b)

[[5 6]
 [2 8]]
[[6 7]
 [2 6]]


In [26]:
a * b

array([[30, 42],
       [ 4, 48]])

In [27]:
###Matrix Multiplication or dot product or vector multiplication

In [28]:
a

array([[5, 6],
       [2, 8]])

In [29]:
b

array([[6, 7],
       [2, 6]])

In [30]:
np.matmul(a, b)

array([[42, 71],
       [28, 62]])

In [1]:
##other way to write multiplication in python

In [3]:
import numpy as np

In [4]:
a = np.random.randint(1, 10,(2, 2))
b = np.random.randint(1, 10,(2, 2))
print(a)
print(b)

[[9 3]
 [9 5]]
[[7 3]
 [1 7]]


In [5]:
a

array([[9, 3],
       [9, 5]])

In [7]:
b

array([[7, 3],
       [1, 7]])

In [8]:
np.matmul(a, b)

array([[66, 48],
       [68, 62]])

In [9]:
###Other way of multiplying matrices

In [10]:
a @ b

array([[66, 48],
       [68, 62]])

In [11]:
a.dot(b)

array([[66, 48],
       [68, 62]])

In [21]:
###matrix vector multiplication

In [5]:
import numpy as np

In [6]:
a = np.random.randint(10,100,(4,4))
a
                    

array([[19, 39, 44, 39],
       [72, 66, 18, 74],
       [72, 71, 37, 72],
       [16, 46, 57, 60]])

In [10]:
b = np.array([2, 3, 4, 5])
b

array([2, 3, 4, 5])

In [11]:
op_vec = a.dot(b)
op_vec

array([526, 784, 865, 698])

In [12]:
op_vec = a @ b
op_vec

array([526, 784, 865, 698])

In [13]:
##Matrix Scalar Multiplication

In [14]:
a

array([[19, 39, 44, 39],
       [72, 66, 18, 74],
       [72, 71, 37, 72],
       [16, 46, 57, 60]])

In [15]:
2 * a

array([[ 38,  78,  88,  78],
       [144, 132,  36, 148],
       [144, 142,  74, 144],
       [ 32,  92, 114, 120]])

In [16]:
###Creating Types of Matrices

In [17]:
##Square Matrices that is m=n or n=m matrix of order m*m or n*n

In [18]:
a

array([[19, 39, 44, 39],
       [72, 66, 18, 74],
       [72, 71, 37, 72],
       [16, 46, 57, 60]])

In [20]:
##Symmetric Matrix

In [23]:
a = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [2, 1, 2, 3, 4],
       [3, 2, 1, 2, 3],
       [4, 3, 2, 1, 2],
       [5, 4, 3, 2, 1]])

In [ ]:
###Triangular Matrix

In [24]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
###Upper Triangular Marix

In [26]:
np.triu(a)

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 3]])

In [ ]:
###Lower Triangular Matrix

In [27]:
np.tril(a)

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [25]:
###Diagonal Matrix

In [30]:
d = np.array([[1, 0, 0],[0, 2, 0],[0, 0, 3]])
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
##Identity Matrix

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
##0peration in Matrix


In [34]:
##Transpose

In [35]:
a = np.random.randint(10, 100,(4, 2))
a                     

array([[54, 51],
       [32, 18],
       [43, 95],
       [64, 22]])

In [36]:
b = a.T
b

array([[54, 32, 43, 64],
       [51, 18, 95, 22]])

In [38]:
#Determinant

In [39]:
x = np.random.randint(10, 100,(4, 4))
x
                      

array([[39, 68, 27, 25],
       [99, 75, 23, 40],
       [75, 75, 99, 30],
       [22, 92, 53, 73]])

In [43]:
import numpy as np

In [44]:
from numpy.linalg import det

In [46]:
det(x)

-13028453.99999998

In [47]:
##Rank of a Matrix

In [49]:
x = np.array([[1, 2, 3]])
np.linalg.matrix_rank(x)

1

In [51]:
a = np.random.randint(10, 100,(4, 4))
np.linalg.matrix_rank(a)

4

In [52]:
a

array([[76, 10, 87, 80],
       [54, 10, 64, 96],
       [44, 38, 39, 44],
       [13, 13, 15, 41]])

In [58]:
import numpy as np

In [59]:
from numpy.linalg import det

In [60]:
import numpy.linalg as la
 

In [56]:
##Eigen Decomposition

In [62]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
A.shape

(3, 3)

In [65]:
eig_values,eig_vectors = np.linalg.eig(A)

In [66]:
eig_values

array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16])

In [67]:
eig_vectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [71]:
Q = eig_vectors
R = np.linalg.inv(Q)
L = np.diag(eig_values)

In [72]:
B = Q.dot(L).dot(R)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [73]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
##Dimension Reduction 

In [74]:
##Page Rank Algorithm in Python

In [77]:
import numpy as np
import numpy.linalg as la

In [ ]:
L = np.array([[0, 1/2, 0, 0],[1/3, 0, 0, 1/2],[1/3, 1/2, 1, 0]])

In [78]:
#Lets set up the initial vector r, 
r = 100*np.ones(4)/4  #this will set the vector with 4 entries of 1/4 x 100 each
r #Display r value

array([25., 25., 25., 25.])

In [ ]:
#Preparation of SVD in Python 

In [87]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
def plotVec(vec, col, alpha = 1):